<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<AssemblyName>con_dms_locker_cmd</AssemblyName>
		<RootNamespace>ConDmsLockerCmd</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Platforms>x64</Platforms>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>false</SelfContained>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.IO.Ports" Version="8.0.0" />
		
	</ItemGroup>

</Project>